language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: 
  - ./build.sh
  - cd test && make && ./generate-xml.sh test-frames
  - cd test && make && ./generate-xml.sh test/error-frames || true
  - cd test && make && ./generate-xml.sh test/unsupported-frames || true
